// Generated by gencpp from file hybrid_navigation/LoadTargetResponse.msg
// DO NOT EDIT!


#ifndef HYBRID_NAVIGATION_MESSAGE_LOADTARGETRESPONSE_H
#define HYBRID_NAVIGATION_MESSAGE_LOADTARGETRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hybrid_navigation
{
template <class ContainerAllocator>
struct LoadTargetResponse_
{
  typedef LoadTargetResponse_<ContainerAllocator> Type;

  LoadTargetResponse_()
    : success(false)  {
    }
  LoadTargetResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::hybrid_navigation::LoadTargetResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hybrid_navigation::LoadTargetResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LoadTargetResponse_

typedef ::hybrid_navigation::LoadTargetResponse_<std::allocator<void> > LoadTargetResponse;

typedef boost::shared_ptr< ::hybrid_navigation::LoadTargetResponse > LoadTargetResponsePtr;
typedef boost::shared_ptr< ::hybrid_navigation::LoadTargetResponse const> LoadTargetResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hybrid_navigation::LoadTargetResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hybrid_navigation::LoadTargetResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hybrid_navigation::LoadTargetResponse_<ContainerAllocator1> & lhs, const ::hybrid_navigation::LoadTargetResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hybrid_navigation::LoadTargetResponse_<ContainerAllocator1> & lhs, const ::hybrid_navigation::LoadTargetResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hybrid_navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hybrid_navigation::LoadTargetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hybrid_navigation::LoadTargetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hybrid_navigation::LoadTargetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hybrid_navigation::LoadTargetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hybrid_navigation::LoadTargetResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hybrid_navigation::LoadTargetResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hybrid_navigation::LoadTargetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::hybrid_navigation::LoadTargetResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::hybrid_navigation::LoadTargetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hybrid_navigation/LoadTargetResponse";
  }

  static const char* value(const ::hybrid_navigation::LoadTargetResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hybrid_navigation::LoadTargetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success \n"
;
  }

  static const char* value(const ::hybrid_navigation::LoadTargetResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hybrid_navigation::LoadTargetResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LoadTargetResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hybrid_navigation::LoadTargetResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hybrid_navigation::LoadTargetResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HYBRID_NAVIGATION_MESSAGE_LOADTARGETRESPONSE_H
