// Generated by gencpp from file hybrid_navigation/LoadTarget.msg
// DO NOT EDIT!


#ifndef HYBRID_NAVIGATION_MESSAGE_LOADTARGET_H
#define HYBRID_NAVIGATION_MESSAGE_LOADTARGET_H

#include <ros/service_traits.h>


#include <hybrid_navigation/LoadTargetRequest.h>
#include <hybrid_navigation/LoadTargetResponse.h>


namespace hybrid_navigation
{

struct LoadTarget
{

typedef LoadTargetRequest Request;
typedef LoadTargetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadTarget
} // namespace hybrid_navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hybrid_navigation::LoadTarget > {
  static const char* value()
  {
    return "4748f0ca5ea091986703d4cb8411ef83";
  }

  static const char* value(const ::hybrid_navigation::LoadTarget&) { return value(); }
};

template<>
struct DataType< ::hybrid_navigation::LoadTarget > {
  static const char* value()
  {
    return "hybrid_navigation/LoadTarget";
  }

  static const char* value(const ::hybrid_navigation::LoadTarget&) { return value(); }
};


// service_traits::MD5Sum< ::hybrid_navigation::LoadTargetRequest> should match
// service_traits::MD5Sum< ::hybrid_navigation::LoadTarget >
template<>
struct MD5Sum< ::hybrid_navigation::LoadTargetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hybrid_navigation::LoadTarget >::value();
  }
  static const char* value(const ::hybrid_navigation::LoadTargetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hybrid_navigation::LoadTargetRequest> should match
// service_traits::DataType< ::hybrid_navigation::LoadTarget >
template<>
struct DataType< ::hybrid_navigation::LoadTargetRequest>
{
  static const char* value()
  {
    return DataType< ::hybrid_navigation::LoadTarget >::value();
  }
  static const char* value(const ::hybrid_navigation::LoadTargetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hybrid_navigation::LoadTargetResponse> should match
// service_traits::MD5Sum< ::hybrid_navigation::LoadTarget >
template<>
struct MD5Sum< ::hybrid_navigation::LoadTargetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hybrid_navigation::LoadTarget >::value();
  }
  static const char* value(const ::hybrid_navigation::LoadTargetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hybrid_navigation::LoadTargetResponse> should match
// service_traits::DataType< ::hybrid_navigation::LoadTarget >
template<>
struct DataType< ::hybrid_navigation::LoadTargetResponse>
{
  static const char* value()
  {
    return DataType< ::hybrid_navigation::LoadTarget >::value();
  }
  static const char* value(const ::hybrid_navigation::LoadTargetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HYBRID_NAVIGATION_MESSAGE_LOADTARGET_H
