// Generated by gencpp from file hybrid_navigation/LoadTargetRequest.msg
// DO NOT EDIT!


#ifndef HYBRID_NAVIGATION_MESSAGE_LOADTARGETREQUEST_H
#define HYBRID_NAVIGATION_MESSAGE_LOADTARGETREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hybrid_navigation
{
template <class ContainerAllocator>
struct LoadTargetRequest_
{
  typedef LoadTargetRequest_<ContainerAllocator> Type;

  LoadTargetRequest_()
    : image_path()  {
    }
  LoadTargetRequest_(const ContainerAllocator& _alloc)
    : image_path(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _image_path_type;
  _image_path_type image_path;





  typedef boost::shared_ptr< ::hybrid_navigation::LoadTargetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hybrid_navigation::LoadTargetRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LoadTargetRequest_

typedef ::hybrid_navigation::LoadTargetRequest_<std::allocator<void> > LoadTargetRequest;

typedef boost::shared_ptr< ::hybrid_navigation::LoadTargetRequest > LoadTargetRequestPtr;
typedef boost::shared_ptr< ::hybrid_navigation::LoadTargetRequest const> LoadTargetRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hybrid_navigation::LoadTargetRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hybrid_navigation::LoadTargetRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hybrid_navigation::LoadTargetRequest_<ContainerAllocator1> & lhs, const ::hybrid_navigation::LoadTargetRequest_<ContainerAllocator2> & rhs)
{
  return lhs.image_path == rhs.image_path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hybrid_navigation::LoadTargetRequest_<ContainerAllocator1> & lhs, const ::hybrid_navigation::LoadTargetRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hybrid_navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hybrid_navigation::LoadTargetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hybrid_navigation::LoadTargetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hybrid_navigation::LoadTargetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hybrid_navigation::LoadTargetRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hybrid_navigation::LoadTargetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hybrid_navigation::LoadTargetRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hybrid_navigation::LoadTargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "65568c775bfbc96c6265c3d13d7e1a07";
  }

  static const char* value(const ::hybrid_navigation::LoadTargetRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x65568c775bfbc96cULL;
  static const uint64_t static_value2 = 0x6265c3d13d7e1a07ULL;
};

template<class ContainerAllocator>
struct DataType< ::hybrid_navigation::LoadTargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hybrid_navigation/LoadTargetRequest";
  }

  static const char* value(const ::hybrid_navigation::LoadTargetRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hybrid_navigation::LoadTargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string image_path\n"
;
  }

  static const char* value(const ::hybrid_navigation::LoadTargetRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hybrid_navigation::LoadTargetRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.image_path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LoadTargetRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hybrid_navigation::LoadTargetRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hybrid_navigation::LoadTargetRequest_<ContainerAllocator>& v)
  {
    s << indent << "image_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.image_path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HYBRID_NAVIGATION_MESSAGE_LOADTARGETREQUEST_H
